name: Update Firebase Projects

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:    # allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm install firebase-admin node-fetch

      - name: Update Firestore
        env:
          FIREBASE_ADMIN_KEY: ${{ secrets.FIREBASE_ADMIN_KEY }}
        run: |
          echo "$FIREBASE_ADMIN_KEY" > serviceAccount.json
          node ./scripts/updateFirestore.mjs
